name: Erlang CI

on:
  push:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26.2-alpine

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: XRef
      run: rebar3 xref
    - name: Linter
      run: rebar3 lint
    - name: Dialyzer
      run: rebar3 as test dialyzer
    - name: Run tests
      run: rebar3 do eunit
